# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-dataa:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always


volumes:
  uptime-kuma-dataa:
    driver_opts:
      size: 200Mi
